version: '3.8'

services:
  # Serviço para o backend NestJS
  app:
    container_name: postplus-original
    build: .
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
    depends_on:
      - postgres
      - localstack
    ports:
      - 3000:3000
    networks:
      - app-network
    command: npm run start:dev

  # Serviço de banco de dados Postgres
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Serviço do Nginx para servir o NestJS
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app-network

  # Serviço do LocalStack (AWS local)
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
      - DEFAULT_REGION=${DEFAULT_REGION}
    ports:
      - "4566:4566"   # Porta principal para os serviços da AWS local
      - "4510-4559:4510-4559"  # Outras portas para interações específicas
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack_data:/var/lib/localstack"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  localstack_data:
  node_modules:
